### ISSUE TITLE
Test with large Smoldyn trajectory

### ISSUE THREAD

**Issue by blairlyons** [simularium/simularium-lambdas#3]
## Use Case
As a developer evaluating the current autoconversion lambda, I want to know how it performs with large data.

## Acceptance Criteria
Test conversion with the Smoldyn min1 and spine examples and note performance, especially how long conversion takes.

## Details
Smoldyn input file links:
- [Min1](https://github.com/ssandrews/Smoldyn/blob/master/examples/S99_more/Min/Min1.txt) should look like [this](https://simularium.allencell.org/viewer?trajFileName=smoldyn_min1.simularium)
- [Spine](https://www.smoldyn.org/archive/Andrews_Arkin_2010/spine.txt) should look like [this](https://simularium.allencell.org/viewer?trajFileName=smoldyn_spine.simularium)

Conversion parameters used in the posted examples are [here](https://github.com/simularium/simularium-models/blob/master/smoldyn/smoldyn_to_simularium.py).

**Comment by ascibisz** [comment]
* There are strict limitations to how much data can be transmitted via the API, and how long a single Lambda function can run when triggered
    *  Lambda REST API payload size limit: 10 MB
    *  Lambda response payload size limit: 6 MB
    *  Lambda function time limit: 15 minutes
* Because of the payload limits, the only way to process >10MB files is to upload the trajectory data to we want to convert to a S3 bucket, add a S3 trigger to the lambda to process the content in S3, and then write to the S3 bucket on completion
* Unfortunately, even when maxing out the processing power for the lambda, this doesn't meet performance needs
     * Spine.txt (smoldyn)-> spine.simularium conversion
		45 MB .txt file -> 100 MB .simularium file
		Took 20 seconds locally, 33 seconds in lambda
     * Min1.txt (smoldyn) -> min1.simularium conversion
		1.1 GB .txt file -> 1.8 GB .simularium file
		Took 6:45 locally, timed out after 15:00 in lambda

* I expect that we'll need to be able to convert files that are over 1 GB in size, so this test indicates that lambda won't be sufficient for our use case. I'd recommend exploring AWS EC2+ECS or AWS Fargate+ECS as potential options for autoconversion
